# Generated by Django 4.2 on 2024-09-07 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 1, 58, 41, 136993, tzinfo=datetime.timezone.utc)),
        ),
    ]
