# Generated by Django 4.2 on 2024-09-07 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customusermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
