# Generated by Django 4.2 on 2024-09-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customusermodel_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(default='user-image.png', upload_to='user'),
        ),
    ]
