# Generated by Django 4.2 on 2024-07-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serivces',
            options={'ordering': ('created_at',)},
        ),
    ]
